### ISSUE TITLE
detective pikachu no encuentra el grupo en telegram

### ISSUE THREAD

**Issue by marcelosab** [gentakojima/detectiveyellowcopyrightedrat#4]
Hola buenas, He instalado en un Ubuntu detective pikachu. También cree un bot con BotFather y le copié el token correctamente en la configuración de detectivepikachu. Se conecta a la base de datos porque me ha validado el usuario con Oak. A la hora de agregar el bot a un grupo, no lo encuentra. El grupo está como supergrupo y el bot tiene permisos de administrador y de acceso a los mensajes. Si podrías echarme una mano por favor...
Te paso el log del momento el cual añado el bot a un grupo de telegram:
![log](https://user-images.githubusercontent.com/36458853/36177797-21f22b54-1117-11e8-9454-82b55250cf19.PNG)

También al iniciar detectivepikachubot.py me muestra este mensaje
![image](https://user-images.githubusercontent.com/36458853/36177908-8030d86e-1117-11e8-87a5-0b92f89cbf0a.png)
Muchas gracias

**Comment by gentakojima** [comment]
El mensaje del final solo es un warning que sí, tengo que arreglar pero no corre prisa. Prefiero no romper nada ahora mismo.

Fíjate en el método que está a partir de la [línea 410](https://github.com/gentakojima/detectiveyellowcopyrightedrat/blob/master/detectivepikachubot.py#L410). Está [ignorando cualquier posible excepción](https://github.com/gentakojima/detectiveyellowcopyrightedrat/blob/master/detectivepikachubot.py#L424) y es una mala práctica (¡sorpresa! ¡el código no es muy bueno!).

Como no veo nada relevante en el log, lo que supongo que ocurre es precisamente esto, que está ocurriendo alguna excepción que se está ignorando. Lo mejor que puedes hacer es cambiar ese pass por una linea de debug. Puedes empezar por algo sencillo como sustituir el `pass` por:

    logging.debug("========= Excepción al entrar al canal")

Puedes encontrar más información sobre el manejo de excepciones en la [documentación de Python](https://docs.python.org/3/tutorial/errors.html).

**Comment by gentakojima** [comment]
Vale, acabo de darme cuenta de lo que pasa. En la [línea 415](https://github.com/gentakojima/detectiveyellowcopyrightedrat/blob/master/detectivepikachubot.py#L415) se pregunta si el nombre de usuario es `detectivepikachubot`, cuando debería utilizarse el que pones en la configuración.

Lo arreglo ahora.

**Comment by gentakojima** [comment]
Intenta ahora. Si el problema sigue, reabre. Gracias!

**Comment by marcelosab** [comment]
Vale, perfecto ha funcionado.
En la linea número 415 he puesto el alias del bot y funciona correctamente. Gracias, eres un crack!
