### ISSUE TITLE
El asistente de raids no funciona.

### ISSUE THREAD

**Issue by marcelosab** [gentakojima/detectiveyellowcopyrightedrat#6]
Buenas, la última parte que me falta es poder crear una raid con el asistente. Cuando hago /raid en un grupo, no me sale ningún asistente y ningún mensaje del bot. Las ubicaciones están activadas y he añadido el excel con todos los gimnasios. He mirado el log pero no entiendo el error. El bot lee bien la tabla incursiones de la base de datos, por lo tanto, salen las incursiones previas que se han hecho.
![image](https://user-images.githubusercontent.com/36458853/36214218-2cbfc612-11a9-11e8-8728-5a18cbededfe.png)
![image](https://user-images.githubusercontent.com/36458853/36214348-97bc0908-11a9-11e8-9f5d-aeb616583eda.png)
Gracias.

**Comment by gentakojima** [comment]
Debería estar arreglado. Prueba a ver.

**Comment by marcelosab** [comment]
Ahora me muestra el asistente pero no me muestra ningún pokémon para añadir.
![image](https://user-images.githubusercontent.com/36458853/36215716-29697c70-11ad-11e8-8196-a1ee152804a6.png)

**Comment by gentakojima** [comment]
Es normal, ya que el bot coge hasta 12 pokémon de entre los más utilizados los últimos 5 días globalmente, pero de 3 en 3. Y solo si hay al menos 3, muestra alguno. Crea una raid de 3 pokemon distintos y vuelve a intentarlo.
